/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  safelist: [
    'bg-slate-950',
    'bg-slate-900',
    'bg-slate-800',
    'bg-slate-700',
    'bg-slate-600',
    'text-slate-100',
    'text-slate-200',
    'text-slate-300',
    'text-slate-400',
    'text-slate-500',
    'text-white',
    'text-blue-400',
    'text-yellow-400',
    'bg-blue-600',
    'bg-yellow-600',
    'border-slate-700',
    'border-slate-800',
    'min-h-screen',
    'flex',
    'items-center',
    'justify-center',
    'rounded-xl',
    'rounded-2xl',
    'rounded-3xl',
    'shadow-lg',
    'shadow-xl',
    'shadow-2xl',
  ],
  theme: {
    extend: {
      colors: {
        slate: {
          950: '#020617',
          900: '#0f172a',
          800: '#1e293b',
          700: '#334155',
          600: '#475569',
          500: '#64748b',
          400: '#94a3b8',
          300: '#cbd5e1',
          200: '#e2e8f0',
          100: '#f1f5f9',
        },
        primary: {
          50: '#eff6ff',
          100: '#dbeafe',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#60a5fa',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
          800: '#1e40af',
          900: '#1e3a8a',
        },
      },
      keyframes: {
        'animate-in': {
          '0%': { opacity: '0', transform: 'translateY(-10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'zoom-in': {
          '0%': { opacity: '0', transform: 'scale(0.95)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        'slide-in-from-right': {
          '0%': { transform: 'translateX(100%)' },
          '100%': { transform: 'translateX(0)' },
        },
        'slide-in-from-left': {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(0)' },
        },
      },
      animation: {
        'animate-in': 'animate-in 0.2s ease-out',
        'fade-in': 'fade-in 0.2s ease-out both',
        'zoom-in': 'zoom-in 0.2s ease-out',
        'slide-in-from-right': 'slide-in-from-right 0.3s ease-out both',
        'slide-in-from-left': 'slide-in-from-left 0.3s ease-out both',
      },
    },
  },
  plugins: [],
}
